/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import DATA.Piloto;
import DATA.PilotoDAO;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

public class TelaPiloto extends javax.swing.JFrame {

    /**
     * Creates new form TelaPiloto
     */
    public TelaPiloto() {
        initComponents();
        preencherTabela();
    }
    
    public void preencherTabela(){
        PilotoDAO dao = new PilotoDAO();
        dao.conectar();
        String nomePiloto = txtNome.getText();
        List<Piloto> listaPilotos = dao.getPilotos(nomePiloto);
        DefaultTableModel tabelaPilotos = (DefaultTableModel) tblPilotos.getModel();
        tblPilotos.setRowSorter(new TableRowSorter(tabelaPilotos));
        tabelaPilotos.setNumRows(0);
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        for(Piloto p : listaPilotos){
            Object[] obj = new Object[]{
                p.getIdPiloto(),
                p.getNome(),
                p.getAltura(),
                p.getPeso(),
                (p.getDataNascimento() != null ? sdf.format(p.getDataNascimento()) : "")
            };
            tabelaPilotos.addRow(obj);
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtAltura = new javax.swing.JTextField();
        txtPeso = new javax.swing.JTextField();
        txtData = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPilotos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CADASTRO PILOTO");

        jLabel1.setText("Id do Piloto");

        jLabel2.setText("Nome do Piloto");

        jLabel3.setText("Altura");

        jLabel4.setText("Peso");

        jLabel5.setText("Data de Nascimento");

        txtNome.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtNomeCaretUpdate(evt);
            }
        });

        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnConsultar.setText("CONSULTAR");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnEditar.setText("EDITAR");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setText("EXCLUIR");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        tblPilotos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Piloto", "Nome do Piloto", "Altura", "Peso", "Data de Nascimento"
            }
        ));
        jScrollPane1.setViewportView(tblPilotos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSalvar)
                        .addGap(18, 18, 18)
                        .addComponent(btnConsultar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtData, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .addComponent(txtPeso)
                            .addComponent(txtAltura)
                            .addComponent(txtNome)
                            .addComponent(txtId))
                        .addGap(13, 13, 13)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnConsultar)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir))
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        Piloto p = new Piloto();
        PilotoDAO dao = new PilotoDAO();
        boolean status;
        int resposta;
        
        p.setIdPiloto(Integer.parseInt(txtId.getText()));
        p.setNome(txtNome.getText());
        p.setAltura(Float.parseFloat(txtAltura.getText()));
        p.setPeso(Float.parseFloat(txtPeso.getText()));
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        try {
            p.setDataNascimento(sdf.parse(txtData.getText()));
        } catch (ParseException ex) {
            Logger.getLogger(TelaPiloto.class.getName()).log(Level.SEVERE, null, ex);
        }
        status = dao.conectar();
        if(status == false){
            JOptionPane.showMessageDialog(null, "Erro de conexão");
        }else{
            resposta = dao.salvar(p);
            if(resposta ==1){
                JOptionPane.showMessageDialog(null, "Dados incluidos com sucesso");
                //limpar os campos
                txtId.setText("");
                txtNome.setText("");
                txtAltura.setText("");
                txtPeso.setText("");
                txtData.setText("");
                //posicionar o curso no campo ID para um novo registro
                txtId.requestFocus();
            }else if(resposta == 1062){
                JOptionPane.showMessageDialog(null, "Piloto já existe no banco");
            }else{
                JOptionPane.showMessageDialog(null, "Erro ao tentar inserir os dados no banco");
            }
            dao.desconectar();
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        PilotoDAO dao = new PilotoDAO();
        boolean status = dao.conectar();
        if(status == false){
            JOptionPane.showMessageDialog(null, "Erro de conexão");
        }else{
            status = dao.excluir(Integer.parseInt(txtId.getText()));
            if(status ==true){
                JOptionPane.showMessageDialog(null, "Piloto excluido com sucesso");
                //limpar os campos
                txtId.setText("");
                txtNome.setText("");
                txtAltura.setText("");
                txtPeso.setText("");
                txtData.setText("");
                //posicionar o curso no campo ID para um novo registro
                txtId.requestFocus();
                //desabilitar o botão
                //btnExcluir.setEnabled(false);
            }else{
                JOptionPane.showMessageDialog(null, "Erro na exclusão do piloto");
            }
            dao.desconectar();
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        String nome = txtNome.getText();
        PilotoDAO dao = new PilotoDAO();
        boolean status = dao.conectar();
        if(status == true){
            Piloto p = dao.consultar(nome);
            if(p == null){
                JOptionPane.showMessageDialog(null,"Piloto não encontrado");
            }else{
                txtId.setText(String.valueOf(p.getIdPiloto()));
                txtAltura.setText(String.valueOf(p.getAltura()));
                txtPeso.setText(String.valueOf(p.getPeso()));
                DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
                String dataFormatada = df.format(p.getDataNascimento()); //converteu a data no padrão BR
                txtData.setText(dataFormatada);
                btnExcluir.setEnabled(true);
            }
            dao.desconectar();
        }else{
            JOptionPane.showMessageDialog(null,"Piloto não encontrado");
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        Piloto p = new Piloto();
        PilotoDAO dao = new PilotoDAO();
        boolean status;
        int resposta;
        
        p.setIdPiloto(Integer.parseInt(txtId.getText()));
        p.setNome(txtNome.getText());
        p.setAltura(Float.parseFloat(txtAltura.getText()));
        p.setPeso(Float.parseFloat(txtPeso.getText()));
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        try {
            p.setDataNascimento(sdf.parse(txtData.getText()));
        } catch (ParseException ex) {
            Logger.getLogger(TelaPiloto.class.getName()).log(Level.SEVERE, null, ex);
        }
        status = dao.conectar();
        if(status == false){
            JOptionPane.showMessageDialog(null, "Erro de conexão");
        }else{
            resposta = dao.atualizar(p); //Executa a ação de atualizar a informação no banco de dados
            if(resposta ==1){
                JOptionPane.showMessageDialog(null, "Dados atualizados com sucesso");
                //limpar os campos
                txtId.setText("");
                txtNome.setText("");
                txtAltura.setText("");
                txtPeso.setText("");
                txtData.setText("");
                //posicionar o curso no campo ID para um novo registro
                txtId.requestFocus();
            }else{
                JOptionPane.showMessageDialog(null, "Erro ao tentar atualizar os dados no banco");
            }
            dao.desconectar();
        }
        
    }//GEN-LAST:event_btnEditarActionPerformed

    private void txtNomeCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtNomeCaretUpdate
        preencherTabela();// TODO add your handling code here:
    }//GEN-LAST:event_txtNomeCaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPiloto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPiloto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPiloto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPiloto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPiloto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPilotos;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPeso;
    // End of variables declaration//GEN-END:variables
}
